
# PyTorch Fundamentals

## 1. Matrices


### Matrices Brief Introduction
- Basic definition: rectangular array of numbers.
- Tensors (PyTorch)
- Ndarrays (NumPy)

**<center> 2 x 2 Matrix (R x C)</center>**

1 | 1 
--- | ---
1 | 1 

**<center> 2 x 3 Matrix </center>**

1 | 1 | 1
--- | ---| ---
1 | 1 | 1 

### 1.1 Creating Matrices

In [0]:
import numpy as np

In [2]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

>  torch and numpy are very similar.

In [0]:
import torch

In [5]:
# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

### 1.2 Create Matrices with Default Values

In [6]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [7]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [8]:
np.random.rand(2, 2)

array([[0.51793241, 0.29558184],
       [0.65971826, 0.71893119]])

In [9]:
torch.rand(2, 2)

tensor([[0.8560, 0.2339],
        [0.5761, 0.6963]])

### 1.3 Seeds for Reproducibility

In [10]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [12]:
# No seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [13]:
# No seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [14]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [15]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [16]:
# Torch No Seed
torch.rand(2, 2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [17]:
# Torch No Seed
torch.rand(2, 2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

**Seed for GPU is different for now...**

In [0]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

### 1.3 NumPy and Torch Bridge

### NumPy to Torch 

In [0]:
# Numpy array
np_array = np.ones((2, 2))

In [20]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [21]:
print(type(np_array))

<class 'numpy.ndarray'>


In [0]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

In [23]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [24]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [25]:
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.uint16)
torch.from_numpy(np_array_new)

TypeError: ignored

<p>It currently accepts <code class="xref py py-attr docutils literal notranslate"><span class="pre">ndarray</span></code> with dtypes of <code class="docutils literal notranslate"><span class="pre">numpy.float64</span></code>,
<code class="docutils literal notranslate"><span class="pre">numpy.float32</span></code>, <code class="docutils literal notranslate"><span class="pre">numpy.float16</span></code>, <code class="docutils literal notranslate"><span class="pre">numpy.int64</span></code>, <code class="docutils literal notranslate"><span class="pre">numpy.int32</span></code>,
<code class="docutils literal notranslate"><span class="pre">numpy.int16</span></code>, <code class="docutils literal notranslate"><span class="pre">numpy.int8</span></code>, <code class="docutils literal notranslate"><span class="pre">numpy.uint8</span></code>, and <code class="docutils literal notranslate"><span class="pre">numpy.bool</span></code>.</p>

In [26]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [27]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [28]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [29]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [30]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])

In [31]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

| NumPy Array Type        | Torch Tensor Type           |
| :-------------: |:--------------:|
| int64     | LongTensor |
| int32     | IntegerTensor |
| uint8      | ByteTensor      |
| float64 | DoubleTensor     |
| float32 | FloatTensor      |
| double | DoubleTensor      |

### Torch to NumPy

In [0]:
torch_tensor = torch.ones(2, 2)

In [33]:
type(torch_tensor)

torch.Tensor

In [0]:
torch_to_numpy = torch_tensor.numpy()

In [35]:
type(torch_to_numpy)

numpy.ndarray

### 1.4 Tensors on CPU vs GPU

In [0]:
# CPU
tensor_cpu = torch.ones(2, 2)

In [0]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [38]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

### 1.5 Tensor Operations

### Resizing Tensor

In [39]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [40]:
print(a.size())

torch.Size([2, 2])


In [41]:
# view() converts tensor to one array tensor
a.view(4)

tensor([1., 1., 1., 1.])

In [42]:
a.view(4).size()

torch.Size([4])

### Element-wise Addition

In [43]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [44]:
b = torch.ones(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [45]:
# Element-wise addition
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [46]:
# Element-wise addition
c = torch.add(a, b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [47]:
# In-place addition
print('Old c tensor')
print(c)

c.add_(a)

print('-'*60)
print('New c tensor')
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New c tensor
tensor([[3., 3.],
        [3., 3.]])


### Element-wise Subtraction

In [48]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [49]:
a - b

tensor([[0., 0.],
        [0., 0.]])

In [50]:
# Not in-place
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [51]:
# Inplace
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


### Element-Wise Multiplication

In [52]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [53]:
a * b

tensor([[0., 0.],
        [0., 0.]])

In [54]:
# Not in-place
print(torch.mul(a, b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [55]:
# In-place
print(a.mul_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


### Element-Wise Division

In [0]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

In [57]:
b / a

tensor([[0., 0.],
        [0., 0.]])

In [58]:
torch.div(b, a)

tensor([[0., 0.],
        [0., 0.]])

In [59]:
# Inplace
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

### Tensor Mean

- $1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55$
- $mean = 55 /10 = 5.5$


In [60]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [61]:
a.mean(dim=0)

tensor(5.5000)

In [62]:
a.mean(dim=1)

IndexError: ignored

In [0]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [64]:
a.size()

torch.Size([2, 10])

In [65]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

## Tensor Standard Deviation

In [66]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)

---
# We've learnt to...
1. Create Matrices
2. Create Matrices with Default Initialization Values
    - Zeros 
    - Ones
3. Initialize Seeds for Reproducibility on GPU and CPU
4. Convert Matrices: NumPy => Torch and Torch => NumPy
5. Move Tensors: CPU => GPU and GPU => CPU
6. Run Important Tensor Operations
    - Element-wise addition, subtraction, multiplication and division
    - Resize
    - Calculate mean 
    - Calculate standard deviation